"""initial: all 5 tables

Revision ID: edac4c069c8c
Revises: 
Create Date: 2026-07-16 10:10:57.635036
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'edac4c069c8c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_spaces',
    sa.Column('agent_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('api_key_hash', sa.String(length=64), nullable=True),
    sa.Column('api_key_prefix', sa.String(length=8), nullable=True),
    # 注意：JSON 默认值必须走 sa.text() 且对「冒号+数字」做 \: 反斜杠转义——
    # 否则 :0 / :5000 被 TextClause 当作绑定参数渲染成 NULL（edac4c 历史损坏根因）；
    # 纯字符串则会被 SQLAlchemy 二次加引号产生畸形 SQL。两者都踩过，勿改。
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{\"decay_per_day\"\\:0.95,\"min_weight\"\\:0.1,\"max_memories\"\\:5000,\"learning_mode\":\"heuristic\"}'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('purged_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('long_term_memories',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('agent_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('weight', sa.Float(), server_default=sa.text('1.0'), nullable=False),
    sa.Column('review_status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_spaces.agent_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_memories_agent_weight', 'long_term_memories', ['agent_id', sa.literal_column('weight DESC')], unique=False, postgresql_where=sa.text('is_deleted = false'))
    op.create_index('idx_memories_search', 'long_term_memories', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('pending_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('agent_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source', sa.String(length=20), server_default=sa.text("'chat'"), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True, comment='Dify conversation_id,审计维度'),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('marked_type', sa.String(length=20), nullable=True),
    sa.Column('dedup_key', sa.String(length=255), nullable=True, comment='幂等键（observation 必填 = 业务方 event_id）'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_spaces.agent_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pending_agent', 'pending_events', ['agent_id', 'created_at'], unique=False)
    op.create_index('idx_pending_dedup', 'pending_events', ['agent_id', 'dedup_key'], unique=True, postgresql_where=sa.text('dedup_key IS NOT NULL'))
    op.create_table('wiki_documents',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('agent_id', sa.UUID(as_uuid=False), nullable=True, comment='NULL = 全局共享'),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False, comment='强制填写,召回时用 tsvector 匹配此字段'),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_spaces.agent_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wiki_search', 'wiki_documents', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('learning_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('agent_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=20), server_default=sa.text("'chat'"), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('event_context', sa.Text(), nullable=False),
    sa.Column('decision_action', sa.String(length=20), nullable=True),
    sa.Column('decision_target', sa.String(length=20), nullable=True),
    sa.Column('memory_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('llm_raw_response', sa.Text(), nullable=True),
    sa.Column('analyzer_mode', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_spaces.agent_id'], ),
    sa.ForeignKeyConstraint(['memory_id'], ['long_term_memories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_logs_agent', 'learning_logs', ['agent_id', 'created_at'], unique=False)

    # --- zhparser full-text search: extension + config + trigger functions + triggers ---
    # Inlined so `alembic upgrade head` is self-contained on any DB;
    # docker init SQL (init-db.sql) only handles the extension side.
    op.execute("CREATE EXTENSION IF NOT EXISTS zhparser")
    op.execute("""
        DO $$ BEGIN
            CREATE TEXT SEARCH CONFIGURATION zhparser (PARSER = zhparser);
        EXCEPTION WHEN duplicate_object OR unique_violation THEN NULL; END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            ALTER TEXT SEARCH CONFIGURATION zhparser ADD MAPPING FOR n,v,a,i,e,l,j WITH simple;
        EXCEPTION WHEN unique_violation THEN NULL; END $$;
    """)
    op.execute("""
        CREATE OR REPLACE FUNCTION memories_search_vector_trigger() RETURNS trigger AS $$
        BEGIN
            NEW.search_vector := setweight(to_tsvector('zhparser', COALESCE(NEW.title, '')), 'A')
                              || setweight(to_tsvector('zhparser', COALESCE(NEW.content, '')), 'B');
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE OR REPLACE FUNCTION wiki_search_vector_trigger() RETURNS trigger AS $$
        BEGIN
            NEW.search_vector := setweight(to_tsvector('zhparser', COALESCE(NEW.title, '')), 'A')
                              || setweight(to_tsvector('zhparser', COALESCE(NEW.description, '')), 'B')
                              || setweight(to_tsvector('zhparser', COALESCE(NEW.content, '')), 'C');
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("CREATE TRIGGER trg_memories_search_vector BEFORE INSERT OR UPDATE ON long_term_memories FOR EACH ROW EXECUTE FUNCTION memories_search_vector_trigger()")
    op.execute("CREATE TRIGGER trg_wiki_search_vector BEFORE INSERT OR UPDATE ON wiki_documents FOR EACH ROW EXECUTE FUNCTION wiki_search_vector_trigger()")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS trg_wiki_search_vector ON wiki_documents")
    op.execute("DROP TRIGGER IF EXISTS trg_memories_search_vector ON long_term_memories")
    op.drop_index('idx_logs_agent', table_name='learning_logs')
    op.drop_table('learning_logs')
    op.drop_index('idx_wiki_search', table_name='wiki_documents', postgresql_using='gin')
    op.drop_table('wiki_documents')
    op.drop_index('idx_pending_agent', table_name='pending_events')
    op.drop_table('pending_events')
    op.drop_index('idx_memories_search', table_name='long_term_memories', postgresql_using='gin')
    op.drop_index('idx_memories_agent_weight', table_name='long_term_memories', postgresql_where=sa.text('is_deleted = false'))
    op.drop_table('long_term_memories')
    op.drop_table('agent_spaces')
    op.execute("DROP FUNCTION IF EXISTS wiki_search_vector_trigger() CASCADE")
    op.execute("DROP FUNCTION IF EXISTS memories_search_vector_trigger() CASCADE")
    op.execute("DROP TEXT SEARCH CONFIGURATION IF EXISTS zhparser")
    # ### end Alembic commands ###
