"""codebase_runs for V1.5a batch audit

Revision ID: ba3603bedd21
Revises: edac4c069c8c
Create Date: 2026-08-18 15:39:29.721272
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ba3603bedd21'
down_revision: Union[str, None] = 'edac4c069c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codebase_runs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('agent_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('repo_path', sa.Text(), nullable=False, comment='客户端上报的仓库标识'),
    sa.Column('commit_sha', sa.String(length=40), nullable=True, comment='蒸馏基线'),
    sa.Column('files_scanned', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='排除清单过滤后的有效文件数'),
    sa.Column('files_excluded', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='被排除数（体积治理可见性）'),
    sa.Column('cards_written', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('cards_skipped_protected', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='修订保护生效次数'),
    sa.Column('tokens_used', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'running'"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_spaces.agent_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cbruns_agent', 'codebase_runs', ['agent_id', sa.literal_column('started_at DESC')], unique=False)
    # 以下三项是 autogenerate 捡到的**存量漂移**（模型早已如此、迁移未跟上），非 V1.5a 需求：
    # api_key_* 的列注释、learning_logs.event_type 20→50（observation event_type 可超 20 字）。
    op.alter_column('agent_spaces', 'api_key_hash',
               existing_type=sa.VARCHAR(length=64),
               comment='SHA-256(space_key)，仅存哈希',
               existing_nullable=True)
    op.alter_column('agent_spaces', 'api_key_prefix',
               existing_type=sa.VARCHAR(length=8),
               comment='space_key 前 8 位，UI 辨认用',
               existing_nullable=True)
    op.alter_column('learning_logs', 'event_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('learning_logs', 'event_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('agent_spaces', 'api_key_prefix',
               existing_type=sa.VARCHAR(length=8),
               comment=None,
               existing_comment='space_key 前 8 位，UI 辨认用',
               existing_nullable=True)
    op.alter_column('agent_spaces', 'api_key_hash',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='SHA-256(space_key)，仅存哈希',
               existing_nullable=True)
    op.drop_index('idx_cbruns_agent', table_name='codebase_runs')
    op.drop_table('codebase_runs')
    # ### end Alembic commands ###
